### ISSUE TITLE
视频上传出错!

### ISSUE THREAD

**Issue by cifaz** [tencentyun/vod-js-sdk-v6#5]
技术vue2.5 vue-cli3 webpack4+, vod-js-sdk-v6 1.4.3

使用中的问题
1.10001 ugc upload | invalid request, 包含你们自己的demo也会出现问题, 签名正常,  已用script导入的类型验证过了

**Comment by idenet** [comment]
我也出现这个错

**Comment by woaiso** [comment]
同样遇到这个问题

**Comment by ganshiqingyuan** [comment]
message: "ugc upload | invalid signature"，
然而signature也是按照文档上的事例生成的，就是无效

**Comment by ganshiqingyuan** [comment]
@cifaz @idenet @woaiso 你们最后都咋解决的

**Comment by hjd31** [comment]
我也报这个错，有谁解决了嘛？
Error: ugc upload | invalid request
    at Uploader.eval (uploader.js:454:1)
    at step (uploader.js:59:1)
    at Object.eval [as next] (uploader.js:40:1)
    at fulfilled (uploader.js:31:1)
